//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chapyEntities : DbContext
    {
        public chapyEntities()
            : base("name=chapyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CpBuilding> CpBuildings { get; set; }
        public DbSet<CpClass> CpClasses { get; set; }
        public DbSet<CpClassStaff> CpClassStaffs { get; set; }
        public DbSet<CpCorporation> CpCorporations { get; set; }
        public DbSet<CpGradeCode> CpGradeCodes { get; set; }
        public DbSet<CpGroup> CpGroups { get; set; }
        public DbSet<CpHoliday> CpHolidays { get; set; }
        public DbSet<CpPosition> CpPositions { get; set; }
        public DbSet<CpSchool> CpSchools { get; set; }
        public DbSet<CpStaff> CpStaffs { get; set; }
        public DbSet<CpStaffType> CpStaffTypes { get; set; }
        public DbSet<CpStartEndDate> CpStartEndDates { get; set; }
        public DbSet<CpTannin> CpTannins { get; set; }
        public DbSet<CpTerm> CpTerms { get; set; }
        public DbSet<CpTimeZone> CpTimeZones { get; set; }
        public DbSet<JapanHoliday> JapanHolidays { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<CpScheduleDetail> CpScheduleDetails { get; set; }
        public DbSet<CpSchedule> CpSchedules { get; set; }
    }
}
