//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpClassStaff
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int StaffId1 { get; set; }
        public Nullable<int> StaffId2 { get; set; }
        public Nullable<int> StaffId3 { get; set; }
        public Nullable<int> StaffId4 { get; set; }
        public Nullable<int> StaffId5 { get; set; }
        public Nullable<int> StaffId6 { get; set; }
        public Nullable<int> NumberOfStaff { get; set; }
        public int TanninId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual CpClass CpClass { get; set; }
    }
}
