//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpClass
    {
        public CpClass()
        {
            this.CpClassStaffs = new HashSet<CpClassStaff>();
            this.CpScheduleDetails = new HashSet<CpScheduleDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int GradeCodeId { get; set; }
        public int SchoolId { get; set; }
        public int TermId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual CpGradeCode CpGradeCode { get; set; }
        public virtual CpSchool CpSchool { get; set; }
        public virtual CpTerm CpTerm { get; set; }
        public virtual ICollection<CpClassStaff> CpClassStaffs { get; set; }
        public virtual ICollection<CpScheduleDetail> CpScheduleDetails { get; set; }
    }
}
