//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpGradeCode
    {
        public CpGradeCode()
        {
            this.CpClasses = new HashSet<CpClass>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int TermId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ICollection<CpClass> CpClasses { get; set; }
        public virtual CpTerm CpTerm { get; set; }
    }
}
