//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpSchedule
    {
        public CpSchedule()
        {
            this.CpScheduleDetails = new HashSet<CpScheduleDetail>();
        }
    
        public int Id { get; set; }
        public int TermID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Chosen { get; set; }
    
        public virtual CpTerm CpTerm { get; set; }
        public virtual ICollection<CpScheduleDetail> CpScheduleDetails { get; set; }
    }
}
