//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpSchool
    {
        public CpSchool()
        {
            this.CpClasses = new HashSet<CpClass>();
            this.CpGroups = new HashSet<CpGroup>();
            this.CpHolidays = new HashSet<CpHoliday>();
            this.CpPositions = new HashSet<CpPosition>();
            this.CpStaffs = new HashSet<CpStaff>();
            this.CpStaffTypes = new HashSet<CpStaffType>();
            this.CpStartEndDates = new HashSet<CpStartEndDate>();
            this.CpTerms = new HashSet<CpTerm>();
            this.CpTimeZones = new HashSet<CpTimeZone>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Representation { get; set; }
        public string PrinceName1 { get; set; }
        public string PrinceName2 { get; set; }
        public string PostCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string HomePage { get; set; }
        public Nullable<byte> UsePass { get; set; }
        public string Password { get; set; }
        public Nullable<int> LimitHour { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ICollection<CpClass> CpClasses { get; set; }
        public virtual CpCorporation CpCorporation { get; set; }
        public virtual ICollection<CpGroup> CpGroups { get; set; }
        public virtual ICollection<CpHoliday> CpHolidays { get; set; }
        public virtual ICollection<CpPosition> CpPositions { get; set; }
        public virtual ICollection<CpStaff> CpStaffs { get; set; }
        public virtual ICollection<CpStaffType> CpStaffTypes { get; set; }
        public virtual ICollection<CpStartEndDate> CpStartEndDates { get; set; }
        public virtual ICollection<CpTerm> CpTerms { get; set; }
        public virtual ICollection<CpTimeZone> CpTimeZones { get; set; }
    }
}
