//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpStaff
    {
        public CpStaff()
        {
            this.CpScheduleDetails = new HashSet<CpScheduleDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int StaffTypeId { get; set; }
        public int PositionId { get; set; }
        public int SchoolId { get; set; }
        public string Name { get; set; }
        public string Hiragana { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Hiragana2 { get; set; }
        public string Name2 { get; set; }
        public Nullable<System.DateTime> beginJob { get; set; }
        public Nullable<byte> jobType { get; set; }
        public string PostCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string HomePage { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string EmerencyAddress1 { get; set; }
        public string EmerencyAddress2 { get; set; }
        public string EmerencyTel { get; set; }
        public Nullable<int> experienceYears { get; set; }
        public string experienceType { get; set; }
        public Nullable<byte> useBus { get; set; }
        public Nullable<System.DateTime> holidayFrom { get; set; }
        public Nullable<int> hodidayNumber { get; set; }
        public string notCombiStaffs { get; set; }
    
        public virtual CpPosition CpPosition { get; set; }
        public virtual ICollection<CpScheduleDetail> CpScheduleDetails { get; set; }
        public virtual CpSchool CpSchool { get; set; }
        public virtual CpStaffType CpStaffType { get; set; }
    }
}
