//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpTerm
    {
        public CpTerm()
        {
            this.CpClasses = new HashSet<CpClass>();
            this.CpClassStaffs = new HashSet<CpClassStaff>();
            this.CpGradeCodes = new HashSet<CpGradeCode>();
            this.CpSchedules = new HashSet<CpSchedule>();
            this.CpTimeZones = new HashSet<CpTimeZone>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int SchoolId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<CpClass> CpClasses { get; set; }
        public virtual ICollection<CpClassStaff> CpClassStaffs { get; set; }
        public virtual ICollection<CpGradeCode> CpGradeCodes { get; set; }
        public virtual ICollection<CpSchedule> CpSchedules { get; set; }
        public virtual CpSchool CpSchool { get; set; }
        public virtual ICollection<CpTimeZone> CpTimeZones { get; set; }
    }
}
