//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CpTimeZone
    {
        public CpTimeZone()
        {
            this.CpScheduleDetails = new HashSet<CpScheduleDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int SchoolId { get; set; }
        public int TermID { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Color { get; set; }
        public string DayOfWeeks { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> RestStartTime1 { get; set; }
        public Nullable<System.DateTime> RestEndTime1 { get; set; }
        public Nullable<System.DateTime> RestStartTime2 { get; set; }
        public Nullable<System.DateTime> RestEndTime2 { get; set; }
        public string ApplyClassed { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ICollection<CpScheduleDetail> CpScheduleDetails { get; set; }
        public virtual CpSchool CpSchool { get; set; }
        public virtual CpTerm CpTerm { get; set; }
    }
}
